## TidyTuesday WK1 media_franchises ##
## jonathon_mifsud ##
## 03/07/19 ##

library(tidyverse)
library(hrbrthemes)
library(ggthemes)
library(ggchicklet)

## Reading in the file ##
media_franchises <- readr::read_csv(
  "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")

# Looking at the data I think this week I would like to make a bar-plot. Franchise has a length of 103 unique titles,
# which may be too lengthy to analyse in this form. Instead, I aim to make a  of the total revenue separated by year.
# I will segment each year to show the contributions of each each type of original media.

## CLEANING ##

# delete duplicates
media_franchises <-
  media_franchises[!duplicated(media_franchises),]

# We have alot of years to work with. Instead of looking at a subset of this I will try creating multiple bins.
#We have 52 individual years so we could break this evenly into 13 bins. I am sure there is a better way to generate the labels!

media_franchises <- media_franchises %>% 
  mutate(original_media = case_when(
  original_media == "Novel" ~ "Books",
  original_media == "Book" ~ "Books",
  original_media == "Visual novel" ~ "Books",
  original_media == "Film" ~ "Movie",
  original_media == "Animated film" ~ "Movie",
  original_media == "Animated series" ~ "TV",
  original_media == "Television series" ~ "TV",
  original_media == "Anime" ~ "TV",
  original_media == "Comic book" ~ "Comic Books",
  original_media == "Manga" ~ "Comic Books",
  original_media == "Cartoon character" ~ "Cartoons",
  original_media == "Cartoon" ~ "Cartoons",
  original_media == "Animated cartoon" ~ "Cartoons",
  original_media == "Comic strip" ~ "Cartoons",
  original_media == "Video game" ~ "Video games",
  original_media == "Greeting card" ~ "Other",
  original_media == "Digital pet" ~ "Other",
  original_media == "Musical theatre" ~ "Other"))

media_franchises$year_created <-
  cut(
    media_franchises$year_created,
    breaks = 9,
    labels = c(
      "1924-1934",
      "1934-1944",
      "1944-1954",
      "1954-1964",
      "1964-1974",
      "1974-1984",
      "1984-1994",
      "1994-2004",
      "2004-2014"))
    
    year_counts <- media_franchises %>%
      group_by(original_media, year_created) %>%
      summarise(total_yearly_revenue_by_original_media = round(sum(revenue)),
                media_count = n())
    
    ## PLOT ##
    
    #This barplot was inspired by a post and wonderful barplot tutorial by @hrbrmstr https://rud.is/b/2019/06/30/make-refreshing-segmented-column-charts-with-ggchicklet/ using the package ggchicklet
    
    year_counts %>%
      ggplot(aes(year_created, total_yearly_revenue_by_original_media, fill = original_media)) +
      geom_chicklet(width = 0.5) +
      scale_y_comma(position = "right") +
      coord_flip() +
      ggthemes::scale_fill_tableau('Superfishel Stone', name = NULL) +
      labs(
        x = NULL ,
        y = "Total revenue generated over time (in billions)",
        fill = NULL,
        title = "Revenue Generated by Media Franchise Powerhouses",
        subtitle = "By Year of Franchise Inception",
        caption = "Source Wikipedia, Plot by @jonathon_mifsud"
      ) +
      theme_ipsum_rc(grid = "X") +
      theme(legend.position = "bottom")
    
    